### ISSUE TITLE
Pretrained model for GQA

### ISSUE THREAD

**Issue by sanjayss34** [airsplay/lxmert#16]
Could you please upload a pretrained model for GQA and put the link in the README? Thank you very much!

**Comment by airsplay** [comment]
Hi,

The weight is available [here](https://drive.google.com/file/d/10I7rrxjR0-N9K-9NHVFImo4nh0qliqbQ/view?usp=sharing). 

Since the main purpose of the code is for pre-training and fine-tuning, it might be better to put the link in this issue.
