### ISSUE TITLE
Parameters that are frozen in fine-tuning?

### ISSUE THREAD

**Issue by sanjayss34** [airsplay/lxmert#2]
Which, if any, parameters are frozen during fine-tuning?

**Comment by airsplay** [comment]
I believe that none of them are frozen for now. The weights could be frozen by not adding them to the optimizer [at here](https://github.com/airsplay/lxmert/blob/3d65149ec5626814e60bf84ae81cf8a9aab43951/src/tasks/nlvr2.py#L64).
