### ISSUE TITLE
How can I reproduce your pre-training result in EMNLP paper?

### ISSUE THREAD

**Issue by jkhong9** [airsplay/lxmert#23]
Hi,

How can I reproduce your pre-training result in EMNLP paper?
Your paper set the epoch for pre-training to 20, but this code's default epoch is 12.
Just setting the epoch to 20 in this code will reproduce your result?
Thank you.

**Comment by airsplay** [comment]
Yep. 

I verified the pre-training script provided in this Github with 20 epochs. It achieves 74.85% on NLVR2 and  69.83% on VQA v2.0. I load the BERT weights in pre-training (by removing the argument `--fromScratch`) thus it is slightly (0.1%) lower than pre-training without loading BERT weights (as shown in the paper). 

I will update the default setup to 20.

**Comment by jkhong9** [comment]
Thank you!
