### ISSUE TITLE
Visual genome features

### ISSUE THREAD

**Issue by JizeCao** [airsplay/lxmert#25]
Are the visual genome visual features extracted from the fine-tuned bottom-up model on the vg dataset or the pretrained one from bottom-up repo?

**Comment by airsplay** [comment]
Sorry... I did not fully understand your question. Could you specify it a little bit more?

Let me try to answer it first but I am not sure whether it is what you want. The Faster R-CNN in [bottom-up repo](https://github.com/peteanderson80/bottom-up-attention) is trained on Visual Genome (excluding COCO minival images). The features I used are extracted from this Faster R-CNN as described [here](https://github.com/airsplay/lxmert#faster-r-cnn-feature-extraction).

**Comment by JizeCao** [comment]
Yeah, my mistake. I misunderstood that the feature extractor is trained on visual genome but nos MSCOCO...
