### ISSUE TITLE
What are the exact 4-dimension spatial features for ROIs?

### ISSUE THREAD

**Issue by JizeCao** [airsplay/lxmert#26]
The author uses a 4-d vector to represent an ROI's spatial feature. What are the exact attributes in the 4-d vector? i.e: (x_center, y_center, height, width) or (x_left_corner, y_left_corner, x_right_corner, y_right_corner)

**Comment by airsplay** [comment]
The order is (x_left_corner, y_top_corner, x_right_corner, y_bottom_corner).

Here is a visualization. Suppose the `box = [x0, y0, x1, y1]`, it annotates an RoI of:
```
0-------------------------------------
 |                                   |
 y0 box[1]   |-----------|           |
 |           |           |           |
 |           |  Object   |           |
 y1 box[3]   |-----------|           |
 |                                   |
H----------x0 box[0]-----x1 box[2]----
 0                                   W
```

Note that some image loaders would swap the order of (H, W) or use a reversed coordinate system for H.  Additional processing is needed.
