### ISSUE TITLE
Extracting Image Features

### ISSUE THREAD

**Issue by sanjayss34** [airsplay/lxmert#3]
When trying to run feature extraction using the docker image, I am running
`CUDA_VISIBLE_DEVICES=4 python extract_nlvr2_image.py --split train`
and I get the error 
`python: can't open file 'extract_nlvr2_image.py': [Errno 2] No such file or directory`
I have installed the docker image using `sudo pull airsplay/bottom-up-attention`. Please let me know how I can fix this. Thank you!

**Comment by airsplay** [comment]
Hi, 

I might need some details about how the docker container is run. But I am trying to give some debugging solution for now.

Could you please try this command while the current working directory is LXMERT_ROOT:
```
docker run --gpus all -v /path/to/nlvr2/images:/workspace/images:ro -v $(pwd)/data/nlvr2_imgfeat:/workspace/features --rm -it airsplay/bottom-up-attention bash
```

After running the command, a new shell would appear (indicating that you are inside a docker container). And please go to `cd /workspace/features` and check whether there is a file `extract_nlvr2_image.py` in it. If not, it means that the folder is not correctly mounted. 

I used `-v` argument to mount the path `data/nlvr2_imgfeat` to the path `/workspace/features` inside the docker container. The file `extract_nlvr2_image.py` is the same as the python file [here](https://github.com/airsplay/lxmert/blob/master/data/nlvr2_imgfeat/extract_nlvr2_image.py).

Hope these help!

**Comment by sanjayss34** [comment]
Thanks. The issue was that `extract_nlvr2_image.py` was not in the `/workspace/features` directory as you said.
