### ISSUE TITLE
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /opt/conda/conda-bld/pytorch_1549630534704/work/aten/src/THC/THCGeneral.cpp:51

### ISSUE THREAD

**Issue by Zzmonica** [airsplay/lxmert#31]
Hi~
When I running VQA Fine-tuning. The tiny mode works fine. But when I running on the whole VQA corpus. I got the above bug. And the torch version is torch 1.0.1. Any suggestion?
Hope your response, thanks!

**Comment by airsplay** [comment]
Sorry... I mostly have no idea on it...  Could you rerun it under the same conda/virtual-env as `tiny'?

**Comment by Zzmonica** [comment]
I already solved it, and it's not about the code settings. I'll close this issue. Thanks for your reply!
