### ISSUE TITLE
problem in feature extraction

### ISSUE THREAD

**Issue by luoruixuan** [airsplay/lxmert#32]
hi,
Thanks a lot for sharing such a useful repo. We are trying to apply it on a new dataset, but we got in trouble during feature extraction.
The link of pretrained Faster-RCNN model seems to be unavailable. Could you please share it on Google Drive or Baidu Drive?
Thank you.

**Comment by airsplay** [comment]
Thanks! 

I have uploaded the pretrained weight to [Google Drive]( https://drive.google.com/drive/folders/1Gq1uLUk6NdD0CcJOptXjxE6ssY5XAuat?usp=sharing) and [Baidu Drive](https://pan.baidu.com/s/1m0mUVsq30rO6F1slxPZNHA) (access code `wwma`). Please check the folder with name `pre_trained_faster_rcnn`.

**Comment by luoruixuan** [comment]
Thanks.
