### ISSUE TITLE
When i use your docker image to extract butd features, should i need to make pycaffe or build Caffe?

### ISSUE THREAD

**Issue by Zhao-Yuting** [airsplay/lxmert#34]
i download your docker image and build my docker container. inside the container, i want to run 'bottom-up-attention/tools/generate_tsv.py'. 
but when i do some import in generate_tsv.py as following:
import _init_paths
from fast_rcnn.config import cfg, cfg_from_file
from fast_rcnn.test import im_detect,_get_blobs
from fast_rcnn.nms_wrapper import nms
from utils.timer import Timer

import caffe
import argparse
import pprint
import time, os, sys
import base64
import numpy as np
import cv2
import csv
from multiprocessing import Process
import random
import json

some error occured:
ImportError                               Traceback (most recent call last)
<ipython-input-1-31bcb3708ecd> in <module>()
      1 import _init_paths
      2 from fast_rcnn.config import cfg, cfg_from_file
----> 3 from fast_rcnn.test import im_detect,_get_blobs
      4 from fast_rcnn.nms_wrapper import nms
      5 from utils.timer import Timer

/workspace/bottom-up-attention/lib/fast_rcnn/test.py in <module>()
     14 import numpy as np
     15 import cv2
---> 16 import caffe
     17 from fast_rcnn.nms_wrapper import nms, soft_nms
     18 import cPickle

/workspace/bottom-up-attention/caffe/python/caffe/__init__.py in <module>()
----> 1 from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
      2 from ._caffe import init_log, log, set_mode_cpu, set_mode_gpu, set_device, Layer, get_solver, layer_type_list, set_random_seed, solver_count, set_solver_count, solver_rank, set_solver_rank, set_multiprocess, Layer, get_solver
      3 from ._caffe import __version__
      4 from .proto.caffe_pb2 import TRAIN, TEST
      5 from .classifier import Classifier

/workspace/bottom-up-attention/caffe/python/caffe/pycaffe.py in <module>()
     11 import numpy as np
     12 
---> 13 from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
     14         RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
     15 import caffe.io

ImportError: No module named _caffe

thank you in advance!

**Comment by yezhengli-Mr9** [comment]
@Zhao-Yuting Have you successfully rewrite `/workspace/features/extract_nlvr2_image.py`? @airsplay @jayleicn

**Comment by yezhengli-Mr9** [comment]
Hi @Zhao-Yuting, I am trying running caffe with `cpu-only`. I finish installing caffe with `cpu-only` but get stuck on modifying [extract_nlvr2_image.py](https://github.com/airsplay/lxmert/blob/master/data/nlvr2_imgfeat/extract_nlvr2_image.py) to `cpu-only` version. 
Have you try to come up with `cpu-only` version of `extract_nlvr2_image.py`?
