### ISSUE TITLE
Could you also provide the fine-tuned model?

### ISSUE THREAD

**Issue by Princesston** [airsplay/lxmert#40]
Thanks for the work, could you also provide the fine-tuned model for VQA, GQA and NLVR2? That would be very helpful, thanks.

**Comment by airsplay** [comment]
VQA: https://github.com/airsplay/lxmert/issues/7
GQA: https://github.com/airsplay/lxmert/issues/16

My disk got cleaned recently and thus do not have NLVR2 in hands...
