### ISSUE TITLE
How to build 'all_ans.json'

### ISSUE THREAD

**Issue by sileod** [airsplay/lxmert#43]
Hi and thank you for sharing your code in such an actually usable way !
The pretraining instructions mention a file name 'all_ans.json', which is required for launching the pretraining instruction, but I coulnd't find  out how to download or build it, and when I run
`bash run/lxmert_pretrain.bash 0,1,2,3 --multiGPU --tiny`
I get
`FileNotFoundError: [Errno 2] No such file or directory: 'data/lxmert/all_ans.json'`
Could anyone tell me how to get all_ans ?
Many thanks

**Comment by airsplay** [comment]
Thanks. The file is contained in the repo here: https://github.com/airsplay/lxmert/blob/master/data/lxmert/all_ans.json.
