### ISSUE TITLE
Could you share the finetuning time cost and the device information?

### ISSUE THREAD

**Issue by moyutianque** [airsplay/lxmert#50]
Especially, VQA and GQA dataset

**Comment by airsplay** [comment]
VQA: 4 (epochs) * 1.5 (hours/epoch) = 6 hours on 1 Titan Pascal.
GQA: 4 (epochs) * 3   (hours/epoch) = 12 hours on 1 Titan Pascal.

**Comment by moyutianque** [comment]
> VQA: 4 (epochs) * 1.5 (hours/epoch) = 6 hours on 1 Titan Pascal.
> GQA: 4 (epochs) * 3 (hours/epoch) = 12 hours on 1 Titan Pascal.

thanks
