### ISSUE TITLE
Making this available at hugging face models directory?

### ISSUE THREAD

**Issue by vibhavagarwal5** [airsplay/lxmert#53]
Hi, 
Are there any plans to make this available at the hugging face transformer models directory? [Here.](https://huggingface.co/models)

**Comment by airsplay** [comment]
The model relies on an additional object detector to process the images, which makes it hard to be integrated into a pure-text repo.

**Comment by vibhavagarwal5** [comment]
I see. Thanks for the quick reply. Pls, close the issue if you feel so.

**Comment by airsplay** [comment]
Closed. Thanks.
