### ISSUE TITLE
entry.py model loading

### ISSUE THREAD

**Issue by ecekt** [airsplay/lxmert#60]
Hello, I am using entry.py to extract the cross-modal representations. If I don't load from a pretrained file and if the args.from_scratch is False, I still get some representations. How are the weights initialized in that case? Is it fine to load the pretrained like this:
```
lx_encoder = LXRTEncoder(max_seq_length=30, args=args_load)
lx_encoder.load(pretrained_file) # 'Epoch20'
```
Best regards.

**Comment by airsplay** [comment]
Lang Encoder would be initialized with BERT weights and other weights are randomly initialized.

**Comment by ecekt** [comment]
Thank you for the response.
