### ISSUE TITLE
how to know the object name from obj id in vg_gqa_imgfeat?

### ISSUE THREAD

**Issue by luomancs** [airsplay/lxmert#66]
hi there, 

I want get the name of objects in an image. In vg_gqa_imgfeat.tsv, we can get the obj_id, I think we should be able to get the each object name by this obj_id right? could you tell how to do it?

Thanks

Man

**Comment by airsplay** [comment]
Thx. Please check [here](https://github.com/peteanderson80/bottom-up-attention/tree/master/data/genome/1600-400-20) for the obj and attr names.

**Comment by luomancs** [comment]
> Thx. Please check [here](https://github.com/peteanderson80/bottom-up-attention/tree/master/data/genome/1600-400-20) for the obj and attr names.

Thanks a lot!
