### ISSUE TITLE
VQA dataset

### ISSUE THREAD

**Issue by deepaknlp** [airsplay/lxmert#75]
Hi @airsplay,

Thank you for releasing the source code and model. 
I would like to know, how did you obtain the following JSON files from the official VQA2.0 questions and annotations.?

![image](https://user-images.githubusercontent.com/14105096/89122209-2a443800-d4e3-11ea-98ef-b57f42c092e9.png)

Thanks,

**Comment by airsplay** [comment]
We take the pre-processing process in [https://github.com/hengyuan-hu/bottom-up-attention-vqa](https://github.com/hengyuan-hu/bottom-up-attention-vqa) and convert the results in a unified JSON format.

**Comment by deepaknlp** [comment]
Thank you @airsplay for the quick response much appreciated.
