### ISSUE TITLE
object and attribute label name for gqa dataset

### ISSUE THREAD

**Issue by alibabadoufu** [airsplay/lxmert#8]
Hi, may I know where I can find the corresponding label name for the object and attribute in gqa dataset? For example {'banana': 128, 'shoes': 100.....}

**Comment by airsplay** [comment]
Yep. Hope this is what you need:
https://github.com/peteanderson80/bottom-up-attention/tree/master/data/genome/1600-400-20

**Comment by alibabadoufu** [comment]
Thanks so much @airsplay
