### ISSUE TITLE
Not able to reproduce GQA(Train + BERT) 56.2

### ISSUE THREAD

**Issue by yix081** [airsplay/lxmert#80]
Hi Thanks for creating this great repo. 
I have trouble reproducing GQA(Train + BERT), which hits 56.2 for GQA test-dev set. My result stops around 54.51 at around 13 epoch. My script is following:

CUDA_VISIBLE_DEVICES=0,6 PYTHONPATH=$PYTHONPATH:./src \
    python src/tasks/gqa.py \
    --train train,valid --valid testdev \
    --llayers 9 --xlayers 5 --rlayers 5 \
    --batchSize 128 --optim bert --lr 1e-4 --epochs 400 \
    --tqdm --output $output ${@:3} --multiGPU 

Is it related to batch size or something else?

**Comment by airsplay** [comment]
Could you please test the model with `--epochs 20` (appendix D of the [paper](https://arxiv.org/pdf/1908.07490.pdf)) instead of `--epochs 400`? The number of maximal epochs would affect the LR schedule. 

(Btw, you might need to add open `-fromScratch` to trigger the pure BERT mode if the code is not modified.)

**Comment by yix081** [comment]
Hi Thanks for your quick reply!! 

I will change epoch number today. 

for -fromScratch, I believe it will be the version that will not load BERT-pre-trained weights, and train everything completely from scratch. is that correct?

**Comment by airsplay** [comment]
Oh! You're right!!! No need for "fromScratch". My bad.

**Comment by yix081** [comment]
I will close this ticket if --epochs 20 solves the problem. Thanks!

**Comment by yix081** [comment]
btw, should the batch size be set as 64 or 128?

**Comment by yix081** [comment]
IT WORKS. THANKS!

**Comment by airsplay** [comment]
Great to know that :)
