### ISSUE TITLE
Model size

### ISSUE THREAD

**Issue by alibabadoufu** [airsplay/lxmert#9]
Hi, do you roughly know how large is your model?

**Comment by airsplay** [comment]
The serialized pretrained model is around 870M.  When loading into GPU memory, the whole model takes around 6G to 8G with a batch of size 32 (single-precision floats).

**Comment by alibabadoufu** [comment]
Thanks @airsplay ! Your codes are very well written and easy to read. Thanks so much for open sourcing the features as well

**Comment by airsplay** [comment]
@alibabadoufu  Thanks for your kind words ~!
