### ISSUE TITLE
Relation between `lxrt.entry.LXRTEncoder` and `lxrt.modeling.LXRTEncoder`.

### ISSUE THREAD

**Issue by yezhengli-Mr9** [airsplay/lxmert#92]
What is the relation between [`lxrt.entry.LXRTEncoder`](https://github.com/airsplay/lxmert/blob/master/src/lxrt/entry.py#L80) and [`lxrt.modeling.LXRTEncoder`](https://github.com/airsplay/lxmert/blob/master/src/lxrt/modeling.py#L520)?

I think  [`lxrt.entry.LXRTEncoder`](https://github.com/airsplay/lxmert/blob/master/src/lxrt/entry.py#L80) is used more often in [`vqa_model.py`](https://github.com/airsplay/lxmert/blob/master/src/tasks/vqa_model.py#L7) and [`gqa_model.py`](https://github.com/airsplay/lxmert/blob/master/src/tasks/gqa_model.py#L7).

**Comment by yezhengli-Mr9** [comment]
> What is the relation between [`lxrt.entry.LXRTEncoder`](https://github.com/airsplay/lxmert/blob/master/src/lxrt/entry.py#L80) and [`lxrt.modeling.LXRTEncoder`](https://github.com/airsplay/lxmert/blob/master/src/lxrt/modeling.py#L520)?
> 
> I think [`lxrt.entry.LXRTEncoder`](https://github.com/airsplay/lxmert/blob/master/src/lxrt/entry.py#L80) is used more often in [`vqa_model.py`](https://github.com/airsplay/lxmert/blob/master/src/tasks/vqa_model.py#L7) and [`gqa_model.py`](https://github.com/airsplay/lxmert/blob/master/src/tasks/gqa_model.py#L7).

It is [`VisualBertForLXRFeature` in `src/lxrt/entry.py`](https://github.com/airsplay/lxmert/blob/master/src/lxrt/entry.py#L93) as well as [`src.lxrt.modeling.LXRTFeatureExtraction`](https://github.com/airsplay/lxmert/blob/master/src/lxrt/modeling.py#L992) that confuses me.

**Comment by Yucheng-Han** [comment]
It makes me confused for quite a long time, too...
